### ISSUE TITLE
[bug] Highlighting only keeps the most recent highlight 

### ISSUE THREAD

**Issue by matwilso** [hypothesis/browser-extension#53] opened 2017-09-20 21:05 UTC
Version: Hypothesis Chrome extension 1.40.0.0

**Steps to repro**
I have found this behavior happens after I "Highlight" something, then click on it again and edit the contents in the sidebar to add an annotation. So adding an annotation to a Highlight.  Then trying to highlight new text leads to this problem.

**Expected behavior**
Highlighting some text on a website and clicking "Highlight" should color the text and should not affect previous highlights.

**Observed behavior**
Only one new highlight is allowed at a time.  Highlighting new text overrides the previous highlight.

![alt](http://coe.utah.edu/~matwilso/media/bug_report.gif)

**Other notes**

Refreshing the page fixes it and causes the expected behavior again, but only saves the most recent highlight from before the refresh. (The overriding bug is persistent, ie. not just a display error).

**Comment by diegodlh** [comment] 2018-08-24 18:37
This sometimes happens to me as well, although steps to reproduce it are not exactly the same as described by @matwilso.
In my case, everything is working OK until at some moment (apparently random) new highlights override the immediate previous one (as opposed to original description, I don't need to "add an annotation to the [previous] highlight" for this to happen).
If I reload the webpage, it usually starts working OK again, but highlights made after the extension began to malfunction are lost.
Another way that seems to fix it is clicking on the highlight so that it appears in the side bar. As if this step was needed to reconnect with the server to start saving highlights again.
This is bug is very frustrating because it usually happens that you don't see your previous highlights when making new ones. So you don't notice they are disappearing. Until you make a highlight next to another, and then it's too late (you've lost a lot already).
The behaviour is very similar to what happens when you try to make a highlight without logging in (highlight isn't saved and no warning is displayed). Maybe this can give us a clue of why this is happening.
Maybe a warning should be shown when the highlight or annotation couldn't be saved successfully (either because of this bug or because one is no longer logged in -and in my case it happens very often that I get logged out for some reason); so the user can tell if he/she can continue highlighting, or has to do something (log in or refresh webpage) before proceeding.

**Comment by matwilso** [comment] 2018-08-24 18:54
I have also noticed that this happens not just in the Chrome browser extension, but also in the Firefox bookmarklet, so it seems to be a more general problem with Hypothesis.

**Comment by ajpeddakotla** [comment] 2018-08-30 22:56
@matwilso and @diegodlh we've tried to reproduce the issues you're seeing but haven't been able to successfully reproduce this highlight behavior. 

Is it possible for you to share a  screenshot or capture a video of what you're seeing? That would be very helpful for us in troubleshooting this bug. I have a hunch that this is one of those more difficult to identify bugs.

**Comment by diegodlh** [comment] 2018-08-30 23:04
Thanks @ajpeddakotla for answering. I have the same hunch. This happens to me quite often, but I'm afraid I don't know how to force it to happen. I have no experience debugging browser extensions. Is there a way I could output verbose information to the browser's console? Or, even better, dump it to some file? So, whenever this happens to me, I have something more informative to analyze and send you. I can send you a video as you suggested, if not, but I think that's way less useful. Thanks!

**Comment by diegodlh** [comment] 2018-08-31 00:06
Here I found a way to reproduce a bug that, not exactly what described in my previous message, can be related to it.
If I select text, then activate the hypothes.is extension, and shortly after choose to highlight the text selected, then the annotation does not appear in the side bar, and is lost if page is reloaded.
As opposed to what I described before, in this case new higlights don't make the previous unsaved one disappear.
I found that it seems to be related to how shortly after activating the extension I do the highlight. See later in the video that if I wait until the previously saved highlights are loaded, then the new one is saved correctly.
Again, this is not the exact same behavior as previously described, but I feel it might be related.
I attach as well a video showing what happens when trying to highlight without being logged-in. This is more similar to what I reported in my previous message.
[screen_record.zip](https://github.com/hypothesis/browser-extension/files/2338320/screen_record.zip)

**Comment by matwilso** [comment] 2018-08-31 03:05
Here is a screen capture of the behavior I described (link will probably only be live until May 2019):
https://pubweb.eng.utah.edu/~matwilso/media/hypo-bug.mp4

**Comment by diegodlh** [comment] 2018-08-31 19:41
Here I attach a recording the behavior described in my message from Aug 24. I was reading and annotating a webpage and at some point _t_ in time (I would say I did nothing in particular, although I can't be 100% sure) highlights would no longer be saved and new ones override immediately previous ones. If I reloaded the page (not shown) all highlights made after time _t_ would be lost. In this video I show how clicking on the last highlight opens the side bar, makes the highlight be saved correctly, and resumes proper behavior.
[Kazam_screencast_00002.mp4.zip](https://github.com/hypothesis/browser-extension/files/2341373/Kazam_screencast_00002.mp4.zip)

**Comment by klemay** [comment] 2018-11-28 15:36
Another user has [reported this issue in Zendesk](https://hypothesis.zendesk.com/agent/tickets/3403). He provides a gif and this link: http://drnissani.net/mnissani/RevolutionarysToolkit/TheMoonIsAHarshMistress.pdf

**Comment by klemay** [comment] 2020-11-09 16:59
I am now unable to reproduce this at any of the URLs mentioned here. I even tried leaving the tab open in the background for ~30mins and coming back to it.

**Comment by klemay** [comment] 2020-11-09 19:54
closing for now - will re-open if we see this come up again

**Closed by klemay** 2020-11-09 19:54 UTC
Labels: unable to reproduce
