### ISSUE TITLE
Annotating youtube videos is really buggy

### ISSUE THREAD

**Issue by semisenioritis** [hypothesis/browser-extension#1096] opened 2023-01-16 16:57 UTC
Whenever I try to annotate videos in a playlist on YouTube (mostly lecture series) with the extension enabled, it seems that the extension doesn't realize the ajax calls and as a result when I move to the next video in the playlist, the sidebar doesn't refresh at all. Because of this, If I want to annotate any new video in the playlist, I have to manually refresh the entire page, close the extension and start it up again. Even then it sometimes doesn't work and needs a second refresh. Point is you never know if the current side bar is linked to the given window or if it is still linked to a previous video.

**Comment by robertknight** [comment] 2023-04-20 10:46
Closing this as a duplicate of https://github.com/hypothesis/product-backlog/issues/1288.

**Closed by robertknight** 2023-04-20 10:46 UTC
