### ISSUE TITLE
Hypothesis browser extension clears out Semantic Reader integrated client if enabled on the Reader page

### ISSUE THREAD

**Issue by kelseym-ai2** [hypothesis/browser-extension#1124] opened 2023-02-10 20:38 UTC
![image](https://user-images.githubusercontent.com/84051438/218191996-a40b32d7-cb16-4181-889b-d6cb7eac1d23.png)

**Steps to repro:**

- Open a browser with the Hypothesis browser installed but disabled
- Visit https://www.semanticscholar.org/reader/8ff840a40d3f1557c55c19d4d636da77103168ce?experiments=pdf_note_taking:enable_note_taking
- Open the Hypothesis side panel by clicking the 'Annotations' button on the righthand side bar, observe it loads properly
- Enable the Hypothesis browser extension
- Observe the side panel gets wiped and the browser extension takes over

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/84051438/218192923-c402fcb1-6772-4a82-bb9d-79f11f76e362.gif)

**Planned workaround:**

The current planned workaround in the Semantic Scholar code is to detect the browser extension presence and then display an error message in the integrated client (figma screenshot below).
![image](https://user-images.githubusercontent.com/84051438/218192223-a0226156-e7a5-49e9-9cf6-9cf15290a670.png)

Methods for detecting browser extension:

- The active Hypothesis client injects several elements into the of the page. The one with rel=hypothesis-client can be used to determine the entry point of the loaded client. 
`<link rel="hypothesis-client" href="https://cdn.hypothes.is/hypothesis/1.1168.0/build/boot.js" type="application/annotator+javascript" data-hypothesis-asset="">`. For the embedded client the URL will begin with cdn.hypothes.is. For the Chrome extension it will begin with chrome-extension://.
- When the Hypothesis client is unloaded, a custom event is dispatched at one of these links. See https://github.com/hypothesis/browser-extension/blob/main/src/unload-client.js

**Comment by robertknight** [comment] 2023-02-11 07:22
This is a result of intentional behavior that was added many years ago to handle the case where Hypothesis is activated on a page that already embeds the extension, due to a constraint that you can't have two different instances of Hypothesis on a page at once (both a technical constraint and to avoid UI conflicts).

The thinking at the time was that the user might want to use the extension instead of the embedded client because the embedded client may use different user accounts (eg. page-specific SSO vs. personal Hypothesis accounts) and different configuration (that may affect the available groups, UI preferences etc.). 

The current logic is:

1. If Hypothesis tries to load and detects another instance of Hypothesis on the page, it aborts
2. If the user disables the browser extension, it unloads any instance of Hypothesis in the page

The consequences of the above are:

- If the page embeds Hypothesis and the user is browsing with Hypothesis activated, the embedded version will win initially
- If the user toggles the browser extension, it will unload the embedded client and load the extension

This preserves the page's normal behavior by default, but provides a way to activate the extension on the page if desired, albeit in a slightly clunky way.

We can reconsider this logic. The main question is "what _should_ happen instead?". The proposed approach of displaying a notice in place of the embedded reader, if the extension is active, actually seems quite reasonable to me.

**Comment by kelseym-ai2** [comment] 2023-02-13 22:44
Thanks for the detailed background and explanation. All that rationale makes sense to me, particularly the point about different user accounts. Just wanted to share the details on this use case on @dwhly's request. Thanks for digging into it!

**Comment by robertknight** [comment] 2023-04-04 14:00
I'm going to close this issue as "working as intended". If we come up to an agreement on some desired alternative behavior that we can implement, then this can be re-opened.

**Closed by robertknight** 2023-04-04 14:00 UTC
